# Generated by Django 4.0.3 on 2022-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
