# Generated by Django 4.0.3 on 2022-08-01 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='assets/imgs-blog/avatar-defualt.jpg', upload_to='customers'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(default="Aucun bio n'est disponible..."),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
