# Generated by Django 4.0.3 on 2022-08-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_remove_customer_email_customer_avatar_customer_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code de transaction'),
        ),
    ]
