# Generated by Django 4.0.3 on 2022-08-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0006_shippingaddress_shipping_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Infos de livraison', 'verbose_name_plural': 'Infos de livraison'},
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code de livraison'),
        ),
    ]
