# Generated by Django 4.0.3 on 2022-08-02 02:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
