# Generated by Django 4.0.3 on 2022-08-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_alter_shippingaddress_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
    ]
