# Generated by Django 4.0.3 on 2022-08-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_remove_customer_avatar_remove_customer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formats_livre', to='commande.versionlivre', verbose_name='Version'),
        ),
    ]
