# Generated by Django 4.0.3 on 2022-08-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='formats_livre', to='commande.versionlivre', verbose_name='Version'),
            preserve_default=False,
        ),
    ]
