# Generated by Django 4.0.3 on 2022-09-24 17:50

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_product_price_currency_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, verbose_name='Prix'),
        ),
    ]
