# Generated by Django 4.0.3 on 2022-09-25 08:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0014_remove_product_price_currency_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
