# Generated by Django 4.0.3 on 2022-10-09 17:17

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0015_alter_shippingaddress_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=200),
        ),
    ]
