# Generated by Django 4.0.3 on 2022-08-12 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='', upload_to='vipost', verbose_name='Image de la publication')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Publication')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modification')),
                ('liked', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Aimé')),
            ],
            options={
                'verbose_name': 'Blog VIP',
                'verbose_name_plural': 'Blogs VIP',
            },
        ),
    ]
