# Generated by Django 4.0.3 on 2022-08-12 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='Aimé'),
        ),
        migrations.AlterField(
            model_name='vipost',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='vipost', verbose_name='Image de la publication'),
        ),
        migrations.AlterField(
            model_name='vipost',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
