# Generated by Django 4.0.3 on 2022-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='asses/imgs-blog/blog-bg.png', upload_to='blogs'),
        ),
    ]
