# Generated by Django 4.0.3 on 2022-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreuser',
            name='code_livre',
        ),
    ]
