# Generated by Django 4.0.3 on 2022-08-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membreuser',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Adresse mail'),
        ),
    ]
