# Generated by Django 4.0.3 on 2022-08-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_remove_membreuser_username_membreuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
    ]
