# Generated by Django 4.0.3 on 2022-08-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0011_alter_membreuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='avatar',
            field=models.ImageField(default='assets/imgs-blog/avatar-defualt.jpg', upload_to='vip'),
        ),
    ]
