# Generated by Django 4.0.3 on 2022-08-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0014_alter_membreuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='avatar',
            field=models.ImageField(default='static/assets/imgs-blog/avatar-default.jpg', upload_to='members'),
        ),
    ]
