# Generated by Django 4.0.3 on 2022-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0016_alter_membreuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membreuser',
            name='password',
        ),
    ]
