# Generated by Django 4.0.3 on 2022-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0017_remove_membreuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8),
        ),
    ]
