# Generated by Django 4.0.3 on 2022-08-30 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compte', '0018_alter_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='membreuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='membreuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Ami'),
        ),
        migrations.AlterField(
            model_name='membreuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='compte.membreuser', verbose_name='Recepteur'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='compte.membreuser', verbose_name='Emeteur'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
