# Generated by Django 4.0.3 on 2022-08-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0019_alter_membreuser_country_alter_membreuser_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='members'),
        ),
    ]
