# Generated by Django 4.0.3 on 2022-08-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0020_alter_membreuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreuser',
            name='avatar',
            field=models.ImageField(default='assets/imgs-blog/avatar-default.jpg', upload_to='members'),
        ),
    ]
